"""
Django settings for CouponHub project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# PyMySQL as MySQLdb for MySQL support
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass

try:
    from dotenv import load_dotenv  # type: ignore
except ImportError:  # pragma: no cover
    def load_dotenv(*args, **kwargs):
        return None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-h_490%*ko76hvldlq%y0i#x(y=+yb6__zk#0csadr1a!s_kktz')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS_ENV = os.getenv('DJANGO_ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',') if host.strip()]
    # Add wildcard support for .render.com, .onrender.com, etc.
    if '.render.com' in ALLOWED_HOSTS or '.onrender.com' in ALLOWED_HOSTS:
        ALLOWED_HOSTS.extend(['couponhub-dp9u.onrender.com', '*.onrender.com'])
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'coupons',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CouponHub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'debug': True,  # Force template debug
        },
    },
]

WSGI_APPLICATION = 'CouponHub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

# Database configuration with dj-database-url support
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Use DATABASE_URL if provided (for Render, Railway, etc.)
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Fallback to manual configuration
    DEFAULT_DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.mysql')
    
    if DEFAULT_DB_ENGINE == 'django.db.backends.mysql':
        default_db_name = os.getenv('DB_NAME', 'couponhub')
    else:
        default_db_name = os.getenv('DB_NAME', str(BASE_DIR / 'db.sqlite3'))
    
    DATABASES = {
        'default': {
            'ENGINE': DEFAULT_DB_ENGINE,
            'NAME': default_db_name,
            'USER': os.getenv('DB_USER', 'root' if DEFAULT_DB_ENGINE == 'django.db.backends.mysql' else ''),
            'PASSWORD': os.getenv('DB_PASSWORD', '1234' if DEFAULT_DB_ENGINE == 'django.db.backends.mysql' else ''),
            'HOST': os.getenv('DB_HOST', 'localhost' if DEFAULT_DB_ENGINE == 'django.db.backends.mysql' else ''),
            'PORT': os.getenv('DB_PORT', '3306' if DEFAULT_DB_ENGINE == 'django.db.backends.mysql' else ''),
        }
    }
    
    if DEFAULT_DB_ENGINE == 'django.db.backends.mysql':
        DATABASES['default']['OPTIONS'] = {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom User Model
AUTH_USER_MODEL = 'coupons.User'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URLs
LOGIN_URL = 'coupons:login'
LOGIN_REDIRECT_URL = 'coupons:home'
LOGOUT_REDIRECT_URL = 'coupons:home'

# Timezone
TIME_ZONE = 'Asia/Ho_Chi_Minh'
LANGUAGE_CODE = 'vi'

# Supabase configuration (Giả lập API các sàn TMĐT)
SUPABASE_URL = os.getenv('SUPABASE_URL', 'https://lxoyximmjfsoswxkctlv.supabase.co')
SUPABASE_ANON_KEY = os.getenv('SUPABASE_ANON_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4b3l4aW1tamZzb3N3eGtjdGx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE1NzMyODIsImV4cCI6MjA0NzE0OTI4Mn0.Zt1xULcGY1Xrj6Qky6DbZw_tf2BiEkq')
SUPABASE_SERVICE_ROLE_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4b3l4aW1tamZzb3N3eGtjdGx2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MzU3MzI4MiwiZXhwIjoyMDc5MTQ5MjgyfQ.TWZEAccU1Glmeb7SU3mhB_GnzL_e23cLagnZLAjnNrQ')
SUPABASE_COUPONS_TABLE = os.getenv('SUPABASE_COUPONS_TABLE', 'coupons')

# External API credentials (Marketplace - Optional)
LAZADA_APP_KEY = os.getenv('LAZADA_APP_KEY', '')
LAZADA_APP_SECRET = os.getenv('LAZADA_APP_SECRET', '')
LAZADA_ACCESS_TOKEN = os.getenv('LAZADA_ACCESS_TOKEN', '')

SHOPEE_PARTNER_ID = os.getenv('SHOPEE_PARTNER_ID', '')
SHOPEE_PARTNER_KEY = os.getenv('SHOPEE_PARTNER_KEY', '')
SHOPEE_SHOP_ID = os.getenv('SHOPEE_SHOP_ID', '')
SHOPEE_ACCESS_TOKEN = os.getenv('SHOPEE_ACCESS_TOKEN', '')

TIKTOK_APP_KEY = os.getenv('TIKTOK_APP_KEY', '')
TIKTOK_APP_SECRET = os.getenv('TIKTOK_APP_SECRET', '')
TIKTOK_SHOP_CIPHER = os.getenv('TIKTOK_SHOP_CIPHER', '')
TIKTOK_ACCESS_TOKEN = os.getenv('TIKTOK_ACCESS_TOKEN', '')
