# Generated by Django 5.2.8 on 2025-11-19 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_category_options_alter_couponcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='couponcategory',
            options={'verbose_name_plural': 'Coupon Categories'},
        ),
        migrations.AlterModelOptions(
            name='usersavedcoupon',
            options={'verbose_name_plural': 'User Saved Coupons'},
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='website_url',
            new_name='logo_url',
        ),
        migrations.AddField(
            model_name='coupon',
            name='affiliate_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(related_name='coupons', through='coupons.CouponCategory', to='coupons.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='quota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='coupons.platform'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('expired', 'Hết hạn')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usersavedcoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='coupons.coupon'),
        ),
        migrations.AlterField(
            model_name='usersavedcoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
    ]
