# Generated by Django 5.2.8 on 2025-11-19 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_category_options_alter_couponcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='api_endpoint',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
