# Generated by Django 5.2.8 on 2025-11-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_platform_api_endpoint_platform_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='api_source_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='synced_from_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='use_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
