# Generated by Django 5.2.8 on 2025-11-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_alter_user_managers_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('shopee', 'Shopee'), ('lazada', 'Lazada'), ('tiktok', 'TikTok Shop')], max_length=20, unique=True)),
                ('api_url', models.URLField(help_text='API Endpoint URL')),
                ('api_key', models.CharField(help_text='API Key/Token', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configurations',
                'db_table': 'api_configurations',
            },
        ),
    ]
