# Generated by Django 5.2.8 on 2025-11-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_apiconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-is_featured', '-priority_score', '-created_at']},
        ),
        migrations.AddField(
            model_name='coupon',
            name='affiliate_commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% hoa hồng (VD: 5.50)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_affiliate',
            field=models.BooleanField(default=False, help_text='Đánh dấu là mã tiếp thị liên kết'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Hiển thị nổi bật'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='priority_score',
            field=models.IntegerField(default=0, help_text='Điểm ưu tiên hiển thị (càng cao càng ưu tiên)'),
        ),
    ]
