# Generated by Django 5.2.8 on 2025-11-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_alter_coupon_options_coupon_affiliate_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='affiliate_commission',
            field=models.CharField(blank=True, help_text='Hoa hồng (VD: 5.5%, 50đ, 100K)', max_length=20, null=True),
        ),
    ]
